# Generated by Django 4.1.3 on 2022-11-02 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='random', max_length=2000)),
                ('description', models.CharField(blank=True, max_length=200000, null=True)),
                ('sku', models.UUIDField(default='79b44e01')),
                ('price', models.BigIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='product_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
